### ISSUE TITLE
Update Language engine based on CDLR and current MediaWiki

### ISSUE THREAD

**Issue by siebrand** [wikimedia/labs-tools-intuition#11]
MediaWiki has implementations for PHP and JavaScript. The current plural rules are most probably aged.

**Comment by Krinkle** [comment]
The "language engine" consists of the following pieces, mostly extracted from MediaWiki:

* **Language data**
  * RTL indication ([/language/rtl.json](https://github.com/Krinkle/intuition/blob/v0.5.3/language/rtl.json) - extracted by [/scripts/getLangData.php](https://github.com/Krinkle/intuition/blob/v0.5.3/scripts/getLangData.php))
  * Fallback chains ([/language/fallbacks.json](https://github.com/Krinkle/intuition/blob/v0.5.3/language/fallbacks.json) - extracted by [/scripts/getLangData.php](https://github.com/Krinkle/intuition/blob/v0.5.3/scripts/getLangData.php))
  * Language names ([mw-classes/Names.php](https://github.com/Krinkle/intuition/blob/v0.5.3/language/mw-classes/Names.php) - copied as-is)
  * Plural, grammar, gender logic for each language ([mw-classes/Language.php](https://github.com/Krinkle/intuition/tree/v0.5.3/language/mw-classes) - copied as-is, most of it unused)
* **Message functions**
  * Parse `{{` syntax in input strings and expand using the Language classes. ([MessageFunctions.php](https://github.com/Krinkle/intuition/blob/v0.5.3/language/MessagesFunctions.php) - local)

Related commits that creates these hacks:
* 664e81fcc0f00df23309eac5ce77a6f520511d3c (Update mw fork)
* f2addb7fbb79909e0089bffd20336d6ad4a80837 (Implement MessageFunctions and initial fork)

**Comment by Krinkle** [comment]
Moved to <https://phabricator.wikimedia.org/T331584>.
